stages:
  - install
  - build-image
  - deploy-image

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: oven/bun
  script:
    - bun install
  artifacts:
    paths:
      - node_modules/

build-image:
  stage: build-image
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker build -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHORT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHORT_SHA"
  after_script:
    - echo "Push Image Complete"
  only:
    - main

deploy-image:
  stage: deploy-image
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker pull "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHORT_SHA"
    - docker rm -f compro-bagiwebsite || true
    - docker run -d -p 3001:3000 --restart always --name compro-bagiwebsite "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHORT_SHA"
  after_script:
    - echo "Deploy Image Success"
  tags:
    - bagiwebsite
  only:
    - main
