stages:
  - install
  - build-image
  - deploy-image

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - bun.lockb

variables:
  DOCKER_IMAGE: '$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA'

install_dependencies:
  stage: install
  image: oven/bun
  script:
    - bun install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
      - bun.lockb

build-image:
  stage: build-image
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    # 1️⃣ Hapus build cache lama agar build selalu fresh
    - rm -rf .next

    # 2️⃣ Build image tanpa cache untuk menghindari penggunaan versi lama
    - docker build --pull --no-cache -t "$DOCKER_IMAGE" .

    # 3️⃣ Push image ke registry
    - docker push "$DOCKER_IMAGE"

    # 4️⃣ Bersihkan docker image yang tidak terpakai untuk menghemat storage
    - docker image prune -af

  after_script:
    - echo "🚀 Push Image Complete"
  only:
    - main

deploy-image:
  stage: deploy-image
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    # 1️⃣ Pastikan image terbaru digunakan
    - docker pull "$DOCKER_IMAGE"

    # 2️⃣ Hentikan container lama jika ada
    - docker rm -f bagiwebste-compro || true

    # 3️⃣ Jalankan container baru dengan auto-restart
    - docker run -d -p 3001:3000 --restart always --name bagiwebsite-compro "$DOCKER_IMAGE"

  after_script:
    - echo "✅ Deploy Image Success 🚀"
  tags:
    - bagiwebsite
  only:
    - main
